name: LADYT
favicon: null
layout_spectrum: 0.7899097576737404
typography_spectrum: 0.03696347703225911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5316260433755815
  lightness: 0.23332644766196609
  saturation: 0.6437584878876805
  rhythmicContrast: 0.36457544937729836
purpose: []
